// vue-frontend/src/components/ExtraSenseCard.vue
<script setup lang="ts">
  import type { GuessTransaction } from '@/types/dto/guess_transaction';

  const props = defineProps<GuessTransaction>();
</script>

<template>
  <div class="col">
    <div class="card mx-2" style="width: 18rem;">
      <div class="card-body">
        <div class="card-title">Extrasense {{ props.guessed_by.slice(0, 5) }}</div>
        <div class="card-text">"Number is {{ props.number }}"</div>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/ExtraSenseCard.tsx
import React from 'react'
import { GuessTransaction } from '../types/dto/guess_transaction'
import { Card } from 'react-bootstrap'


export const ExtraSenseCard = (props: GuessTransaction) => {
  return (
    <Card style={{ width: '18rem', }} className="mx-2">
      {/* <Card.Img variant="top" src="holder.js/100px180" />*/}
      <Card.Body>
        <Card.Title>Extrasense {props.guessed_by}</Card.Title>
        <Card.Text>
          He thinks your number is {props.number}
        </Card.Text>
      </Card.Body>
    </Card>
  )
}
