// frontend/src/components/EnterNumber.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import {Button, Col, Form, Row} from 'react-bootstrap';
import { checkAnswers } from '../network/checkExtrasenseAnswers';
import { Formik } from 'formik';
import * as Yup from 'yup';

const ERROR_MESSAGE = 'Please enter positive two-digit number!';
const TYPE_ERROR_MESSAGE = 'Must be a number';

const numberSchema = Yup.object().shape({
  number: Yup.number()
    .min(10, ERROR_MESSAGE)
    .max(99, ERROR_MESSAGE)
    .required()
    .typeError(TYPE_ERROR_MESSAGE),
});

export default function EnterNumber() {
  const navigate = useNavigate();
  return (
    <Row className='mt-4'>
      <Col></Col>
      <Col xs={4}>
        <h1>Enter two-digit number</h1>
        <Formik
          initialValues={{number: 10}}
          validationSchema={numberSchema}
          onSubmit={values => {
            checkAnswers(values.number);
            navigate("/");
          }}
        >
          {({handleSubmit, handleChange, values, errors, touched}) => (
            <Form noValidate onSubmit={handleSubmit}>
              <Form.Group className="mb-3" controlId="formNumber">
                <Form.Label>A number</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Enter guessed number"
                  name="number"
                  onChange={handleChange} 
                  value={values.number}
                  isInvalid={!!errors.number}
                />
                <Form.Control.Feedback type="invalid">
                  {errors.number}
                </Form.Control.Feedback>
              </Form.Group>
              <Button variant="primary" type='submit'>
                Send your number to server...
              </Button>
            </Form>
          )}
        </Formik>
      </Col>
      <Col></Col>
    </Row>
  );
};

// vue-frontend/src/components/EnterNumber.vue
<script setup lang="ts">

  import { useForm } from 'vee-validate';
  import { object, number } from 'yup';
  import { toTypedSchema } from '@vee-validate/yup';
  import { checkAnswers } from '@/network/checkExtrasenseAnswers';
  import router from '@/router';
  const { handleSubmit } = useForm({
    validationSchema: toTypedSchema(object().shape({
      number: number().min(10, "Too low!")
      .max(99, "Too much!").required("Please enter a number")
      .typeError("Must be a number").default(10),
    })),
  });

  const onSubmit = handleSubmit((values) => {
    checkAnswers(values.number);
    router.push("/");
  });
</script>

<template>
  <div class="row mt-4">
    <div class="col"></div>
    <div class="col xs-4">
      <h1>Enter two-digit number</h1>
      <form @submit="onSubmit">
        <div class="mb-3">
          <label for="numberInput" class="form-label">Enter a number</label>
          <input type="number" class="form-control" id="numberInput" aria-describedby="numberHelp">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    <div class="col"></div>
  </div>
</template>
